如果已经引入spring data jpa的时候，导致springboot识别不了用哪一个api
问题：
```
Caused by: java.lang.NoSuchMethodError: javax.persistence.Table.indexes()[Ljavax/persistence/Index;

````